### ISSUE TITLE
getting error on PointsParser.java

### ISSUE THREAD

**Issue by saraladewi** [thevysh/android-maps-directions#2]
--------- beginning of crash
2019-09-12 21:14:14.297 5106-5106/com.hfad.los E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hfad.los, PID: 5106
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
        at com.hfad.los.PointsParser.onPostExecute(PointsParser.java:63)
        at com.hfad.los.PointsParser.onPostExecute(PointsParser.java:23)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by rr2964** [comment]
Did you manage to fix this bug?
