### ISSUE TITLE
Using maps on Fragment not on Activity... Facing this error

### ISSUE THREAD

**Issue by SuyogAdhikari** [thevysh/android-maps-directions#6]
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 6300
    java.lang.ClassCastException: com.example.myapplication.DashboardActivity cannot be cast to com.example.myapplication.DIrectionHelpers.TaskLoadedCallback
        at com.example.myapplication.DIrectionHelpers.PointsParser.<init>(PointsParser.java:25)
        at com.example.myapplication.DIrectionHelpers.FetchURL.onPostExecute(FetchURL.java:42)
        at com.example.myapplication.DIrectionHelpers.FetchURL.onPostExecute(FetchURL.java:16)
        at android.os.AsyncTask.finish(AsyncTask.java:673)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:690)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by JFAndersson** [comment]
Hi! Did you manage to figure it out? Currently I'm stuck at the same problem.
